name = "[DBAH] Organized Crime"
author = "bennysc"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2abf80c152633a065653d8d1c36f4f85cb986c393be9ab369c9c4b924bafaa86"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
