name = "[DBAH] Organized Crime"
author = "bennysc"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93bed191d976e9a7f6891c3755581d63e3f1cf8e671a7b7dc7e3afb29c7a66ab"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
