name = "[DBAH] Organized Crime"
author = "bennysc"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b5fe281e7259ae6c99be51d39ec9e830610b9843a20bcf2617516a40f4c9be9"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
